version: '3.1'
services:
  teravoz-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "4000:4000"
    links:
      - db
      - redis
    environment:
      DB_ADDR: db
      DB_USER: teravoz_user
      DB_PASS: teravoz
      DB_SCHEMA: teravoz
      REDIS_ADDR: redis
    depends_on:
      - db
      - redis
    networks:
      - app-network

  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - app-network

  client:
    build:
      context: teravoz-challenge-client
      dockerfile: Dockerfile
    ports:
        - "80:80"
    links:
        - teravoz-service
    depends_on:
        - teravoz-service
    networks:
        - app-network
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'teravoz'
      MYSQL_USER: 'teravoz_user'
      MYSQL_PASSWORD: 'teravoz'
      MYSQL_ROOT_PASSWORD: 'teravoz'
    networks:
      - app-network
    ports:
      - '3306:3306'
    expose:
        - '3306'
    volumes:
        - my-db:/var/lib/mysql
volumes:
  my-db:

networks:
  app-network:
    driver: bridge